name: Build Flutter App

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android App Bundle (For Google Play)
        run: flutter build appbundle

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android App Bundle (.aab)
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload Android APK (.apk)
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS App Check
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install macOS Dependencies
        run: sudo gem install cocoapods

      - name: Build iOS App (No Codesign)
        run: |
          flutter pub get
          flutter build ios --release --no-codesign
